name: container-signing-and-verifying
on:
  push:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: build-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/sheurich/boulder
          tags: type=sha,format=long

      - name: Get Git commit timestamps
        id: timestamp
        run: echo "timestamp=$(git log -1 --pretty=%ct)" >> $GITHUB_OUTPUT

      - name: Build and Push container images
        env:
          SOURCE_DATE_EPOCH: ${{ steps.timestamp.outputs.timestamp }}
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Sign and verify the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          REPO: ${GITHUB_REPOSITORY}
          WORKFLOW: ${GITHUB_WORKFLOW}
          REF: ${GITHUB_REF#refs/heads/}
          ID: "https://github.com/${REPO}/.github/workflows/${WORKFLOW}@${GITHUB_REF}"
          ISSUER: "https://token.actions.githubusercontent.com"
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
          cosign verify ${images} \
            --certificate-identity=${ID} \
            --certificate-oidc-issuer=${ISSUER}
